codecov:
  branch: main

coverage:
  status:
    project: off
    patch: off

ignore:
  - "python/adb_bot/games"
  - "python/adb_bot/game.py"
  - "python/adb_bot/adb.py"
  - "python/adb_bot/commands"
  - "python/tests"
  # Wails3
  - "main.go"
  - "internal/app"
  - "internal/games"
  - "internal/hotkeys"
  - "internal/process"
  # Wails2 remove later
  - "app.go"
  - "app*.go"
  - "internal/processmanager.go"
  - "internal/ipc"


flags:
  windows-latest:
    carryforward: true
  macos-latest:
    carryforward: true
