[book]
authors = ["yulesxoxo"]
language = "en"
src = "src"
title = "yulesxoxo AdbBot Documentation"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/yulesxoxo/AdbBot"
edit-url-template = "https://github.com/yulesxoxo/AdbBot/edit/main/docs/{path}"
