/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type ProfileIndex = number
export type Args = string[]
export type Label = string
export type RootModelNoneType = null
export type ProfileIndex1 = number
/**
 * @minItems 3
 * @maxItems 3
 */
export type RootModelTupleDictStrAnyDictStrAnyStr = [unknown, unknown, unknown]
export type ProfileIndex2 = number
export type Trigger = ("adb-settings-updated" | "game-settings-updated")
/**
 * @minItems 1
 */
export type Profiles1 = [string, ...(string)[]]
/**
 * Theme Enum.
 */
export type Theme = ("catppuccin" | "cerberus" | "crimson" | "fennec" | "modern" | "mona" | "nosh" | "nouveau" | "pine" | "rose" | "seafoam" | "terminus" | "vintage" | "vox" | "wintry")
/**
 * Locale Enum.
 */
export type Locale = ("en" | "jp" | "vn")
export type CloseButtonShouldMinimizeTheWindow = boolean
export type DesktopNotifications = boolean
export type DiscordWebhook = string
export type LoggingLevel = ("DEBUG" | "INFO" | "WARNING" | "ERROR" | "FATAL")
export type ShutdownAfterTasks = boolean
export type GameTitle = string
export type Label1 = string
export type Args1 = string[]
export type CustomLabel = (string | null)
export type Category = (string | null)
export type Tooltip = (string | null)
export type MenuOptions = MenuOption[]
export type Categories = string[]
export type SettingsFile = (string | null)
export type DeviceId = (string | null)
export type ActiveTask = (string | null)
export type Timestamp = number
export type Index = number

/**
 * Commands Input and Output Schemas
 */
export interface Commands {
start_task: {
input: StartTaskBody
output: RootModelNoneType
}
stop_task: {
input: ProfileContext
output: RootModelNoneType
}
debug: {
input: ProfileContext
output: RootModelNoneType
}
get_adb_settings_form: {
input: ProfileContext
output: RootModelTupleDictStrAnyDictStrAnyStr
}
get_game_settings_form: {
input: ProfileContext
output: RootModelTupleDictStrAnyDictStrAnyStr
}
get_profile_state: {
input: ProfileContext
output: RootModelNoneType
}
cache_clear: {
input: CacheClear
output: RootModelNoneType
}
_generate_app_settings_model: {
input: void | undefined
output: AppSettings
}
_generate_profile_state_update_model: {
input: void | undefined
output: ProfileStateUpdate
}
}
export interface StartTaskBody {
profile_index: ProfileIndex
args: Args
label: Label
[k: string]: unknown
}
export interface ProfileContext {
profile_index: ProfileIndex1
[k: string]: unknown
}
export interface CacheClear {
profile_index: ProfileIndex2
trigger: Trigger
[k: string]: unknown
}
/**
 * App Settings model.
 */
export interface AppSettings {
profiles?: Profiles
ui?: UserInterface
notifications?: Notifications
logging?: Logging
advanced?: Advanced
[k: string]: unknown
}
/**
 * Profile Settings model.
 */
export interface Profiles {
profiles?: Profiles1
[k: string]: unknown
}
/**
 * UI Settings model.
 */
export interface UserInterface {
theme?: Theme
locale?: Locale
close_should_minimize?: CloseButtonShouldMinimizeTheWindow
[k: string]: unknown
}
/**
 * Notification Settings model.
 */
export interface Notifications {
desktop_notifications?: DesktopNotifications
discord_webhook?: DiscordWebhook
[k: string]: unknown
}
/**
 * Logging settings model.
 */
export interface Logging {
level?: LoggingLevel
[k: string]: unknown
}
/**
 * Advanced Settings model.
 */
export interface Advanced {
shutdown_after_tasks?: ShutdownAfterTasks
[k: string]: unknown
}
export interface ProfileStateUpdate {
state: ProfileState
timestamp: Timestamp
index: Index
[k: string]: unknown
}
export interface ProfileState {
game_menu: (GameGUIOptions | null)
device_id: DeviceId
active_task: ActiveTask
[k: string]: unknown
}
export interface GameGUIOptions {
game_title: GameTitle
menu_options: MenuOptions
categories: Categories
settings_file?: SettingsFile
[k: string]: unknown
}
export interface MenuOption {
label: Label1
args: Args1
custom_label?: CustomLabel
category?: Category
tooltip?: Tooltip
[k: string]: unknown
}
